### ISSUE TITLE
Service is running but does nothing to fan

### ISSUE THREAD

**Issue by balfred** [L33thium/xu4fanctl#1]
I have followed the instructions exactly and none of this code seems to work on my xu4. Looking at the code I cant seem to find a problem and even debugged by adding logging and it appears to hit the right function calls like main() for example but the fan behavior is not modifying as the script dictates. There is probably a step missing in your install steps in README.md

**Comment by L33thium** [comment]
Hi, thanks for your report.
I'm french and my english isnot perfect, so my instructions maybe not clear, i don't know.
Maybe your board does not reach 85° in your attempts ?
It's normal if the fan is stopped at script starts, the code starts it only when one of the core reach 85° or more.
lower the values of hiTmp and loTmp to 60 and 50 or less like me when i wrote the code.
Also check if the path "/sys/devices/odroid_fan.14/" exists on your board, there is no error management in the code at the moment.
