### ISSUE TITLE
A Few Changes

### ISSUE THREAD

**Issue by brando56894** [L33thium/xu4fanctl#2]
First off I had to change /sys/devices/odroid_fan.14 to odroid_fan.13 to get the fan to even work

(I'm using the XU4 on Ubuntu 15.10)

Then I had to place the service file in /usr/lib/systemd/system (not /etc/systemd/system as you suggest) to get "systemctl enable fanctl" to work correctly, otherwise it would say "Failed to execute: Invalid operation"

Finally, in order to get it to start correctly via "systemctl enable fanctl" I had to copy fanctl.py from /root to /etc and modify the service file to have it point to /etc/fanctl.py instead of /root/fanctl.py

After those changes it works just fine :)

**Comment by L33thium** [comment]
thanks for your comment. I run Debian on my xu4, kernel and systemd seems different from Ubuntu.

**Comment by L33thium** [comment]
Changes are made + bonus deb file ready to install
